import { NextResponse } from 'next/server';
import { supabase, getImageUrl, getTownImagePath } from '@/lib/supabase';
import staticImagesData from '@/data/static-images.json';
import expertConfirmedData from '@/data/expert-confirmed-detailed.json';
// Optional user-specific curated sets
import patImagesData from '@/data/static-images-pat.json';
// Stage-2 paramilitary relabel audit worklist (priority-ordered: A+B+E -> Declan -> C -> D)
// See economic-flag-classification/cascade/docs/STAGE2_RELABEL_HANDOFF.md
import auditImagesData from '@/data/static-images-audit.json';
// Note: static-images-mai.json will be generated by the dataset curation script
// and may not exist initially. We will import conditionally at runtime.

export async function GET(request: Request) {
  console.log("[API] GET /api/images-static called");
  const url = new URL(request.url);
  const userParam = (url.searchParams.get('user') || '').trim();
  const userLower = userParam.toLowerCase();
  console.log(`[API] images-static user=${userParam || 'n/a'}`);
  
  try {
    // If a user-specific curated static dataset exists, serve that directly
    // This bypasses Supabase sources to ensure deterministic curated sets
    if (userLower === 'pat') {
      const curated = Array.isArray(patImagesData) ? patImagesData : [];
      return NextResponse.json({
        success: true,
        metadata: {
          source: 'static-images-pat',
          total_images: curated.length,
          with_composites: curated.filter((img: any) => img.has_composite).length,
          user: userParam
        },
        images: curated
      });
    }
    if (userLower === 'audit' || userLower === 'brandon') {
      // Stage-2 paramilitary relabel worklist — priority order A+B+E -> Declan -> C -> D.
      // See economic-flag-classification/cascade/docs/STAGE2_RELABEL_HANDOFF.md.
      const curated = Array.isArray(auditImagesData) ? auditImagesData : [];
      const transformed = curated.map((img: any) => {
        const town = (img.town || '').toString();
        const filename = (img.filename || '').toString();
        const townPath = getTownImagePath(town, filename);
        const pathUrl = getImageUrl(townPath);

        let compositeUrl: string | null = null;
        if (img.has_composite) {
          try {
            let compFilename: string | null = null;
            if (img.composite_image && typeof img.composite_image === 'string') {
              const parts = img.composite_image.split('/');
              compFilename = parts[parts.length - 1] || null;
            } else if (filename) {
              compFilename = `composite_${filename}`;
            }
            if (compFilename) {
              const compTownPath = getTownImagePath(town, compFilename);
              compositeUrl = getImageUrl(compTownPath);
            }
          } catch {
            compositeUrl = null;
          }
        }

        return {
          town,
          path: pathUrl,
          filename,
          composite_image: compositeUrl,
          has_composite: Boolean(compositeUrl)
        };
      });

      return NextResponse.json({
        success: true,
        metadata: {
          source: 'supabase-audit',
          total_images: transformed.length,
          with_composites: transformed.filter((img: any) => img.has_composite).length,
          user: userParam,
          queue_lock: userLower === 'brandon' ? 'forced-audit-for-brandon' : undefined,
          review_reason_tag: 'stage2-relabel-2026-04'
        },
        images: transformed
      });
    }
    if (userLower === 'may') {
      try {
        // Dynamically load May's curated dataset if present
        const module = await import('@/data/static-images-may.json');
        const mayImagesData: any[] = (module as any).default || (module as any);
        if (Array.isArray(mayImagesData) && mayImagesData.length > 0) {
          // Map curated items to Supabase public URLs for robustness
          const transformed = mayImagesData.map((img: any) => {
            const town = (img.town || '').toString();
            const filename = (img.filename || '').toString();
            const townPath = getTownImagePath(town, filename);
            const pathUrl = getImageUrl(townPath);

            let compositeUrl: string | null = null;
            // Prefer the provided composite filename if present; otherwise infer
            if (img.has_composite) {
              try {
                let compFilename: string | null = null;
                if (img.composite_image && typeof img.composite_image === 'string') {
                  const parts = img.composite_image.split('/');
                  compFilename = parts[parts.length - 1] || null;
                } else if (filename) {
                  compFilename = `composite_${filename}`;
                }
                if (compFilename) {
                  const compTownPath = getTownImagePath(town, compFilename);
                  compositeUrl = getImageUrl(compTownPath);
                }
              } catch {
                compositeUrl = null;
              }
            }

            return {
              town,
              path: pathUrl,
              filename,
              composite_image: compositeUrl,
              has_composite: Boolean(compositeUrl)
            };
          });

          return NextResponse.json({
            success: true,
            metadata: {
              source: 'supabase-may',
              total_images: transformed.length,
              with_composites: transformed.filter((img: any) => img.has_composite).length,
              user: userParam
            },
            images: transformed
          });
        }
      } catch (e) {
        console.warn('[API] No static-images-may.json found yet; falling back to default');
      }
    }

    // Check if we have the image_metadata table in Supabase
    const { data: tableExistsCheck, error: tableCheckError } = await supabase
      .from('image_metadata')
      .select('count()', { count: 'exact', head: true });
    
    // If the table exists, use it
    if (!tableCheckError && tableExistsCheck) {
      console.log("[API] Using Supabase image_metadata table");
      
      // Fetch images from Supabase instead of filesystem
      const { data: images, error, count } = await supabase
        .from('image_metadata')
        .select('*', { count: 'exact' })
        .limit(3000);
        
      if (error) {
        console.error("[API] Error fetching images:", error.message);
        throw error;
      }
      
      console.log(`[API] Retrieved ${count} images from Supabase`);
      
      // Process images to include full URLs
      const processedImages = images.map(img => {
        // Calculate full URLs for images
        const imagePath = getImageUrl(img.storage_path);
        
        // Calculate composite URL if available
        let compositeUrl = null;
        if (img.has_composite && img.composite_path) {
          compositeUrl = getImageUrl(img.composite_path);
        }
        
        return {
          town: img.town,
          path: imagePath,
          filename: img.filename,
          composite_image: compositeUrl,
          has_composite: img.has_composite
        };
      });
      
      console.log(`[API] Successfully processed ${processedImages.length} images from Supabase`);
      
      // Apply expert-confirmed curation instead of false positive filtering
      const curatedImages = applyExpertConfirmedCuration(processedImages);
      
      console.log(`[API] Curated ${curatedImages.length} expert-confirmed images from Supabase`);
      
      // Return curated images
      return NextResponse.json({
        success: true,
        metadata: {
          source: 'supabase',
          curation: 'expert-confirmed',
          total_images: curatedImages.length,
          with_composites: curatedImages.filter(img => img.has_composite).length,
          curation_stats: {
            original_count: processedImages.length,
            curated_count: curatedImages.length,
            curation_rate: ((curatedImages.length / processedImages.length) * 100).toFixed(1) + '%'
          }
        },
        images: curatedImages
      });
    } else {
      // If the table doesn't exist yet or we got an error, fall back to static images
      console.log("[API] Falling back to static images");
      
      const isProduction = process.env.VERCEL || process.env.NODE_ENV === 'production';
      
      // Ensure we have staticImages data
      if (!staticImagesData || !Array.isArray(staticImagesData) || staticImagesData.length === 0) {
        console.error("[API] Static images data is missing or empty!");
        throw new Error("Static images data is missing");
      }
      
      // Process static images for production environment if needed
      let processedImages = staticImagesData;
      if (isProduction) {
        console.log("[API] Adjusting static image paths for production");
        
        processedImages = staticImagesData.map(image => {
          // Extract town and filename from the path
          const pathParts = image.path.split('/');
          const filename = pathParts[pathParts.length - 1];
          const town = image.town.toUpperCase().replace(/ /g, '_');
          
          // Construct the storage path
          const storagePath = `${town}/${filename}`;
          
          // Get full URL from Supabase
          const imagePath = getImageUrl(storagePath);
          
          // Handle composite image if present
          let compositeUrl = null;
          if (image.composite_image && image.has_composite) {
            const compositePathParts = image.composite_image.split('/');
            const compositeFilename = compositePathParts[compositePathParts.length - 1];
            compositeUrl = getImageUrl(`${town}/${compositeFilename}`);
          }
          
          return {
            town: town,
            path: imagePath,
            filename: filename,
            composite_image: compositeUrl || image.composite_image,
            has_composite: image.has_composite
          };
        });
      }
      
      console.log(`[API] Using ${processedImages.length} static images`);
      
      // Apply expert-confirmed curation instead of false positive filtering
      const curatedImages = applyExpertConfirmedCuration(processedImages);
      
      console.log(`[API] Curated ${curatedImages.length} expert-confirmed images from static data`);
      
      return NextResponse.json({
        success: true,
        metadata: {
          source: 'static-images',
          curation: 'expert-confirmed',
          total_images: curatedImages.length,
          with_composites: curatedImages.filter(img => img.has_composite).length,
          isProduction: isProduction,
          curation_stats: {
            original_count: processedImages.length,
            curated_count: curatedImages.length,
            curation_rate: ((curatedImages.length / processedImages.length) * 100).toFixed(1) + '%'
          }
        },
        images: curatedImages
      });
    }
  } catch (error) {
    console.error("[API] Error processing images:", error);
    
    // Last resort fallback - return sample images
    try {
      console.log("[API] Using emergency fallback with sample images");
      
      // Create a small sample of test images
      const sampleImages = [
        {
          town: "SAMPLE",
          path: "https://quinfer.github.io/flag-examples/union-jack/example1.jpg",
          filename: "sample-union-jack.jpg",
          has_composite: false
        },
        {
          town: "SAMPLE",
          path: "https://quinfer.github.io/flag-examples/ulster-banner/example1.jpg",
          filename: "sample-ulster-banner.jpg",
          has_composite: false
        },
        {
          town: "SAMPLE",
          path: "https://quinfer.github.io/flag-examples/irish-tricolour/example1.jpg",
          filename: "sample-tricolour.jpg",
          has_composite: false
        }
      ];
      
      return NextResponse.json({
        success: true,
        metadata: { 
          source: "emergency-fallback",
          curation: "sample-images",
          error: error instanceof Error ? error.message : String(error),
          total_images: sampleImages.length,
        },
        images: sampleImages
      });
    } catch (fallbackError) {
      console.error("[API] Emergency fallback also failed:", fallbackError);
      return NextResponse.json({
        success: false,
        error: "Failed to load images from all sources",
        images: []
      });
    }
  }
}

/**
 * Apply expert-confirmed curation to filter images
 * Only returns images that have been verified by experts as containing flags
 */
function applyExpertConfirmedCuration(images: any[]): any[] {
  try {
    // Create a set of expert-confirmed image IDs for fast lookup
    const expertConfirmedSet = new Set(Object.keys(expertConfirmedData));
    
    // Filter images to only include expert-confirmed ones
    const curatedImages = images.filter(image => {
      // Extract the image ID from the filename (handle _box0 suffix)
      const imageId = image.filename.replace('_box0.jpg', '.jpg');
      return expertConfirmedSet.has(imageId);
    });
    
    console.log(`[CURATION] Filtered ${images.length} images to ${curatedImages.length} expert-confirmed images`);
    
    return curatedImages;
  } catch (error) {
    console.error("[CURATION] Error applying expert-confirmed curation:", error);
    // If curation fails, return all images as fallback
    return images;
  }
}
